---
title: "STA 4102 Project"
author: "Jaedin Hernandez"
date: "`r Sys.Date()`"
output: html_document
---

### Background

Numerous wells utilized for drinking water in Bangladesh and South Asian nations are contaminated with naturally occurring arsenic, impacting an estimated 100 million individuals. Arsenic is recognized as a cumulative poison, where exposure heightens the risk of cancer and other diseases, with the associated risks appearing to correlate directly with the level of exposure.

A research team from United States and Bangladesh measured the arsenic in the wells and labeled them "safe" for wells below 0.5 units of hundreds of micrograms per liter of arsenic or "unsafe" for those above 0.5. A few years later they returned and recorded the family units who switched wells, and those who did not.

We shall perform a logistic regression analysis to understand the factors that led to the locals switching wells based on the information that their well was unsafe. We will consider the following as predictors:

-   Distance (in meters) to the closest safe well.

-   The arsenic level of the respondent's well (hundreds of micrograms per liter).

-   Whether any members of the household are active in community organizations (1=yes, 0=no).

-   The number of years of education (presumably of the most educated member of the household).

This data will be integral to political leaders within Araihazar upazila, Bangladesh. With the results of this experiment, will be able to adjust their target audience for future potential health risks based on the regression coefficients and the probability $\pi_{i}$ of switching wells based on the predictors. This experiment will also give results for how to improve the country as a whole. We can use the logistic regression model to determine if Bangladesh should spend the most money on building more wells, improving education, or flat out trying to get rid of the arsenic problem all together.

### Analysis

The following code reads the data into R, provides the summary statistics, and sets up the vectors / matrices

$y=(Y_1, .., Y_n)^\top,$

$Z$ is the $n \times 5$ matrix whose $i$th row is $z_i^\top,$

$1_n$ is an $n$-dimensional vector of all ones

as needed to perform maximum likelihood estimation for the logistic regression model.

```{R}
wells <- read.table(file=url("https://michaeljauch.github.io/STA4102Data/wells.txt"), sep=" ", header=TRUE)
n <- nrow(wells)
y <- wells[,c("switch")]
ones <- rep(1, n)
Z <- as.matrix(cbind(ones, wells[, c("arsenic", "dist","assoc","educ")]))

## INITIAL VALUES
x = c(0,0,0,0,0)
itr = 10
x.values = matrix(0,itr+1,5)
x.values[1,] = x
summary(wells)
```

Looking at the summary statistics we notice that more than 57% of the total respondents switched wells after being notified of the danger. We can also see that less than half of all respondents have family members are active in community organizations.

The following code provides histograms to view the frequency for the numeric variables (arsenic, dist, and educ).

```{R}
Arsenic <- wells$arsenic
hist(Arsenic, xlab="Arsenic Level", col="lightgreen", xlim=c(0, 10), breaks=40)

Distance <- wells$dist
hist(Distance, xlab="Distance From Safe Well", col="tan", breaks=40)

Education <- wells$educ
hist(Education, xlab="Years of Education", col="darkred", xlim=c(0,20), breaks=20)
```

In the following two code chunks we calculate and return the gradient and the hessian of the log likelihood. Further details can be found in the comments.

```{R}
## OBJECTIVE FUNCTION AND DERIVATIVES
g = function(beta, y, Z){
  n <- length(y) # Create a variable n = # of observations
  ones <- rep(1, n) # Create a length n vector of ones
  # Create the b vector 
  b <- rep(0, n) # Initial b as a vector of zeros. 
  for(i in 1:n){
    b[i] <- log(1 + exp(Z[i,] %*% beta))
  }
  # Calculate and return the log likelihood 
  return(y %*% Z %*% beta - b %*% ones)
}

g.prime = function(beta, y, Z){
  n <- length(y) # Create a variable n = # of observations
  # Create the pi vector 
  pi_vec <- rep(0, n) # Initial pi_vec as a vector of zeros. 
  for(i in 1:n){
    pi_vec[i] <- 1/(1 + exp(-Z[i,] %*% beta))
  }
  # Calculate and return the gradient of the log likelihood 
  return(t(Z) %*% (y - pi_vec))
}
```

```{R}
g.2prime=function(beta, y, Z){
  n <- length(y) # Create a variable n = # of observations
  # Create pi vector and a vector w of the diagonal elements of W
  pi_vec <- rep(0, n) # Initial pi_vec as a vector of zeros. 
  w <- rep(0, n) # Initial w as a vector of zeros. 
  for(i in 1:n){
    pi_vec[i] <- 1/(1 + exp(-Z[i,] %*% beta))
    w[i] <- pi_vec[i]*(1-pi_vec[i])
  }
  # Calculate and return the Hessian of the log likelihood 
  return(-t(Z) %*% diag(w) %*% Z)
}

```

Here we will preform newtons method to find our maximum likelihood estimate.
```{R}
## MAIN
for(i in 1:itr){
  x = x - solve(g.2prime(x, y, Z)) %*% g.prime(x, y, Z)
  x.values[i+1,] = x
}
```

```{R}
x
```
Here we can break down our maximum likelihood estimation for each predictor variable:

-   Arsenic(0.467021588) indicates that for each one unit increase in arsenic, the log-odds of switching wells increases by about 47%

-   Distance(-0.008961102) indicates that for each one meter increase in distance from the nearest safe well, the log-odds of switching wells decreases by about 0.896%

-   Association(-0.124299982) indicates that if any members of the household are active in community organizations, the log-odds of switching wells decreases which could indicate that increased social support or access to information about wells through community organizations could lead to less urgency in switching wells

-   Education(0.042446614) suggests that as the number of years of maximum education in the household increases, the log-odds of switching wells will also increase.

```{R}
g.prime(x, y, Z)
```

We notice that we have a very small gradient estimate for each predictor. This paired with small maximum likelihood estimates between -1\<X\<1 provide significant evidence that newtons method has converged and our maximum likelihood estimation has been reached.

### Model fitting

The following three segments of code plots Y (the probability $\pi_{i}$ of switching wells) based on X (each numeric predictor(arsenic, distance, education)).

```{R}
zgrid <- seq(0.510, 9.65, length.out=10000)
z2med <- median(Z[,2])
z3med <- median(Z[,3])
z4med <- median(Z[,4])
z5med <- median(Z[,5])
plot(x=zgrid, y=1/(1 + exp(-1*x[1] - zgrid*x[2] - z3med*x[3] - z4med*x[4] - z5med*x[5])), type="l", ylab="Probability of Switching", xlab="Arsenic Level", main="Probability of Switching by Arsenic Level")
```

Using this graph, we can determine that the amount of arsenic found in the well greatly impacts the probability that a family switches to a safer well. It appears as though as the arsenic level gets closer to 10, the chance of switching wells significantly approaches 1.0 or 100% reaching nearly 98% as the arsenic rises to only 8.0.

```{R}
zgrid <- seq(0.387, 339.531, length.out=10000)
z2med <- median(Z[,2])
z4med <- median(Z[,4])
z5med <- median(Z[,5])
plot(x=zgrid, y=1/(1 + exp(-1*x[1] - z2med*x[2] - zgrid*x[3] - z4med*x[4] - z5med*x[5])), type="l", ylab="Probability of Switching", xlab="Distance From Safe Well", main="Probability of Switching by Distance")
```

By looking at the graph above we can understand that the probability of switching to a safer well is significantly decreased when there is a greater distance between the household and the nearest safe well. As the distance from a safe well decreases, we can observe a significant increase in the probability of switching to it and vise versa.

```{R}
zgrid <- seq(5.00, 15.000, length.out=10000)
z2med <- median(Z[,2])
z3med <- median(Z[,3])
z4med <- median(Z[,4])

plot(x=zgrid, y=1/(1 + exp(-1*x[1] - z2med*x[2] - z3med*x[3] - z4med*x[4] - zgrid*x[5])), type="l", ylab="Probability of Switching Wells", xlab="Education Level", main="Probability of Switching by Education")

```

The graph above shows that the relationship between the probability of switching to a safer well, and the education level within the family is nearly directly proportional. This helps us understand that the lower the education level of the household, the lower chance there is of switching to a safer drinking well.

### Conclusion

As a leader in Bangladesh, it would be wise based on this analysis to specifically target those with a lower education level when notifying the public about a potential health risk. This is determined by the nearly linear relationship observed between education level and probability of switching wells. We can also determine that more money spent on education would significantly improve the likelihood of citizens heeding the warning of a potential public health crisis.

We can also observe that within this situation specifically, building more wells would significantly improve the rate of safe well users. This is due to the clear discrepancy between the rate of switching wells for households that are closer to a safe well and those who are more than 100 meters away from the nearest safe well. If increasing the amount of wells is not possible, another option would be to increase volume of housing near the concentration of safe wells.

Furthermore the amount of arsinec found in respondents well plays appears to play a significant role in whether they switch or not with a switch becoming more likely as the arsinec level rises above 2.0. We can conclude from this that it would not be effective spending money and time fixing the arsenic contamination when the majority of those with highly unsafe levels are expected to switch wells regardless.

Further analysis is necessary to include more variables such as respondent age (average of respondent household) as well as total income level of the household. Older respondents may be more likely to switch wells due to being more susceptible to health complications and higher income respondents may have a higher probability of switching due to having more resources to aid in switching. (i.e a car, second home, etc...).

Our logistic regression model is, however, limited as we have an accurate model of only the numeric variables (educ, arsenic, dist) and not binary predictor's like association. Although logistic regression can identify a relationship between our predictors and whether they switched wells, it does not prove direct causation from any of them. Furthermore, these limitations must be considered when interpreting the results of our analysis and moving forward with direct action.
